#ifndef __CLIMIT_H_
#define __CLIMIT_H_

#define REQUEST_BODY_LENGTH_MAX 60 * 1024

#define DATETIME_LEN_MAX 64
#define FILE_NAME_LEN_MAX 256
#define IP_ADDRESS_LEN_MAX 20

#define ENDPOINT_LEN_MAX 64

#define SQL_SIZE_SMALL 2048

#define USERNAME_MAX 64
#define PASSWORD_MAX 64

#define KAFKA_BROKERS_LEN_MAX 128

#endif  // __CLIMIT_H_
